name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    services:
      dynamodb:
        image: amazon/dynamodb-local:latest
        ports:
        - 8000:8000
      minio:
        image: bitnami/minio:latest
        env:
          MINIO_ACCESS_KEY: localtest
          MINIO_SECRET_KEY: localtest
        ports:
        - 9000:9000
        options: --name minio-server
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - name: Install minio-client
      run: wget https://dl.min.io/client/mc/release/linux-amd64/mc && chmod +x mc && ./mc alias set localtest http://localhost:9000 localtest localtest
    
    - name: Create Minio bucket
      run: ./mc mb localtest/localtest || echo "noop"
    
    - name: Create Dynamo table
      run: aws dynamodb create-table --endpoint-url http://localhost:8000 --region us-west-2
                --table-name localkvstore
                --attribute-definitions
                    AttributeName=KeyPrefix,AttributeType=S
                    AttributeName=ValueKey,AttributeType=S
                --key-schema AttributeName=KeyPrefix,KeyType=HASH AttributeName=ValueKey,KeyType=RANGE
                --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 || echo "noop"

    - name: Build
      run: make ci-build

    - name: Test
      run: make ci-test
